[versions]
jvmTarget = "1.8"
gradlePlugin = "8.1.0"
kotlin = "1.9.10"
ksp = "1.8.10-1.0.9"
kotlinCompilerExtensionVersion = "1.5.3"
kotlinAndroid = "1.9.10"
kotlinMultiplatform = "1.9.10"
compose = "1.5.2"
androidLibrary = "8.1.1"
kodeview = "0.7.0"

[libraries]
kodeview = { group = "dev.snipme", name = "kodeview", version.ref = "kodeview" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlinMultiplatform" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library", version.ref = "androidLibrary" }