[versions]
jvmTarget = "1.8"
gradlePlugin = "8.1.0"
kotlin = "1.9.10"
ksp = "1.8.10-1.0.9"
kotlinCompilerExtensionVersion = "1.5.1"
kotlinAndroid = "1.9.10"
kotlinMultiplatform = "1.9.10"
compose = "1.5.1"
composeCompiler = "1.5.1"
androidLibrary = "8.0.0"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlinMultiplatform" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library", version.ref = "androidLibrary" }